const LOGIN_CLICKED = 'LOGIN_CLICKED';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';

const OLD_PASSWORD_CHANGE = 'OLD_PASSWORD_CHANGE';
const NEW_PASSWORD_CHANGE = 'NEW_PASSWORD_CHANGE';
const CONFIRM_PASSWORD_CHANGE = 'CONFIRM_PASSWORD_CHANGE';
const UPDATE_PASSWORD_CALL = 'UPDATE_PASSWORD_CALL';
const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';


const FORM_IMAGE_BASE64 = 'FORM_IMAGE_BASE64';
const SIGNATURE_IMAGE_BASE64 = 'SIGNATURE_IMAGE_BASE64';

export {
  LOGIN_CLICKED,
  LOGIN_SUCCESS,
  LOGIN_FAILED,

  OLD_PASSWORD_CHANGE,
  NEW_PASSWORD_CHANGE,
  CONFIRM_PASSWORD_CHANGE,
  UPDATE_PASSWORD_CALL,
  UPDATE_PASSWORD_SUCCESS,
  UPDATE_PASSWORD_FAILED,

  FORM_IMAGE_BASE64,
  SIGNATURE_IMAGE_BASE64
};
