# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FieldTrack' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for FieldTrack

  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase'

  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # React-Native is not great about React double-including from the Podfile
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

  # pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end

      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end

  target 'FieldTrack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FieldTrackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


